baseURL = "https://g5search.github.io/opex-runbook/"
languageCode = "en-us"
title = "OpEx Runbook"
theme = "hugo-theme-air"
canonifyURLs = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4

[params]
	author="G5 OpEx"
	description="Documentation for all things OpEx Development & Testing"

	# Repository
	provider = "GitHub"
	repo_url = "https://g5search.github.io/opex-runbook/"

	logo = "images/g5-logo.png"
	favicon = "images/g5-logo.png"

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/overrides.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
		primary = "g5-midnight-blue"
		accent  = "g5-blue-gray"

	[params.font]
		text = "Roboto"
		code = "Roboto Mono"

[social]
	slack   = "team-opex"

[[menu.main]]
	name   = "Getting Started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Prerequisites"
	url    = "prerequisites/"
	weight = 10

[[menu.main]]
	name   = "Installation"
	url    = "installation/"
	weight = 10

[[menu.main]]
	name   = "General Testing Info"
	url    = "general-testing-info/"
	weight = 10

[[menu.main]]
	name   = "Unit Testing"
	url    = "unit-testing/"
	weight = 10

[[menu.main]]
	name   = "Regression Testing"
	url    = "regression-testing/"
	weight = 10

[[menu.main]]
	name   = "Smoke Testing"
	url    = "smoke-testing/"
	weight = 10

[outputs]
	home = [ "HTML", "JSON" ]
	page = [ "HTML" ]